### ISSUE TITLE
投稿插件：Version对文章增加历史记录功能

### ISSUE THREAD

**Issue by innc11** [typecho-fans/plugins#100]
项目地址：https://github.com/innc11/Version
简介：对文章增加历史记录功能

对git subtree看了半天好像把自己绕晕了还是不太会，还需要多学习学习，在这之前还是提交ISSUSE投稿的好

##  插件功能

可以在文章被保存时记录一个历史，如果文章内容丢失或者后悔了可以随时回退到之前的版本

## 图片

![overview2](https://res.innc11.cn/pictures/version/2020-07-26152730.png)

![overview](https://res.innc11.cn/pictures/version/QQ20200726152008.png)

**Comment by jzwalk** [comment]
使用git subtree是要上传源码到这里允许社区修改吗？如果只是加入TeStore列表编辑[TESTORE.MD](https://github.com/typecho-fans/plugins/blob/master/TESTORE.md)增加指向你自己目录的链接信息即可。确认一下哈

**Comment by innc11** [comment]
是的，我想上传源代码并允许社区修改

**Comment by jzwalk** [comment]
哦了，4a4283e。感谢你对社区的贡献和支持！:)

**Comment by innc11** [comment]
谢谢啦
