### ISSUE TITLE
TeStore 无法加载列表

### ISSUE THREAD

**Issue by benzBrake** [typecho-fans/plugins#106]
报错
主机是腾讯轻量香港，HTTPS确认过可以访问，curl https 没问题，是缺少什么php组件吗
```
Class 'DOMDocument' not found
```

**Comment by otsorg** [comment]
请问服务器的php版本是?

**Comment by benzBrake** [comment]
> 
> 
> 请问服务器的php版本是?

docker容器，alpine基础映像，caddy2 + php7.3

**Comment by otsorg** [comment]
用 phpinfo() 输出查看是否缺少xml 扩展 如果是就安装一下

**Comment by otsorg** [comment]
PHP 7.0:

Ubuntu: apt-get install php7.0-xml
CentOS / Fedora / Red Hat: yum install php70w-xml
PHP 7.1:

Ubuntu: apt-get install php7.1-xml
CentOS / Fedora / Red Hat: yum install php71w-xml
PHP 7.2:

Ubuntu: apt-get install php7.2-xml
CentOS / Fedora / Red Hat: yum install php72w-xml
PHP 7.3:

Ubuntu: apt-get install php7.3-xml
CentOS / Fedora / Red Hat: yum install php73w-xml
PHP 7.4:

Ubuntu: apt-get install php7.4-xml
CentOS / Fedora / Red Hat: yum install php74w-xml

**Comment by benzBrake** [comment]
> 
> 
> PHP 7.0:
> 
> Ubuntu: apt-get install php7.0-xml
> CentOS / Fedora / Red Hat: yum install php70w-xml
> PHP 7.1:
> 
> Ubuntu: apt-get install php7.1-xml
> CentOS / Fedora / Red Hat: yum install php71w-xml
> PHP 7.2:
> 
> Ubuntu: apt-get install php7.2-xml
> CentOS / Fedora / Red Hat: yum install php72w-xml
> PHP 7.3:
> 
> Ubuntu: apt-get install php7.3-xml
> CentOS / Fedora / Red Hat: yum install php73w-xml
> PHP 7.4:
> 
> Ubuntu: apt-get install php7.4-xml
> CentOS / Fedora / Red Hat: yum install php74w-xml

已经排查出来是缺少php-dom扩展

**Comment by otsorg** [comment]
HI,你好可以加我微信 icccme 我啦您进开发群 这样效率更高点
