### ISSUE TITLE
【bug】LoveKKComment 插件无法发送评论审核通过邮件，原作者表示不再维护，请朋友们修复下

### ISSUE THREAD

**Issue by xueshanlinghu** [typecho-fans/plugins#107]
我最近在使用插件 LoveKKComment，1.0.5 版本，使用的 typecho 版本为 1.1 (17.10.30)。目前经过各种测试，发现其他各项功能都正常。但是使用SMTP发送`评论审核通过`的邮件时异常，无法发出。

原始 github 项目地址为：[https://github.com/ylqjgm/LoveKKComment](https://github.com/ylqjgm/LoveKKComment)

原作者已经将该项目标记为已完成，不允许提 Issue。我给原作者发邮件，原作者明确表示因个人原因，这款插件不再维护，因此我就我查出的可能的原因说一下，因本人 PHP 水平有限，只能大概定位问题无法解决，请社区的朋友们维护修复下，谢谢！

经过测试，我发现问题可能出在插件的 Plugin.php 这个文件中的这个地方，我只截取其中的一部分代码：

```php
static public function sendMail($commentId, $isApproved = FALSE)
    {	
	
        $commentId = 11;
	
        // 重新获取评论数据
        $comment = self::getWidget('Comments', 'coid', $commentId);
        // 收件人地址
        $address = $comment->mail;
		
        // 上级评论对象
        $parentComment = NULL;
        // 不是帖子发表者
        if ( $comment->authorId != $comment->ownerId ) {
            // 获取作者信息
            $author = self::getWidget('Users', 'uid', $comment->ownerId);
            // 收件地址
            $address = $author->mail;
            // 上级评论
            $parentComment = NULL;
        }
		
        // 评论回复
        if ( 0 < $comment->parent ) {
            // 获取上级对象
            $parentComment = self::getWidget('Comments', 'coid', $comment->parent);
            // 是否获取到且用户ID不同或邮件地址不同
            if ( isset($parentComment->coid) && $comment->mail != $parentComment->mail ) {
                // 收件地址
                $address = $parentComment->mail;
            }
        }
```

其中 `$commentId = 11;` 这一行是我测试时添加的。因为我发现，这个函数进来，是无法获取 commentId 的，为空，这就导致找不到对应的评论，然后就找不到对应要回复给谁的邮箱了。当直接指定 ID 时发现可以正常发送邮件等，因此应该就是 commentId 为空的问题。

希望能有大神能修复此问题，谢谢！

**Comment by rakiy** [comment]
我追了下，似乎这个并不存在问题？你什么环境呢

**Comment by xueshanlinghu** [comment]
您好，我在虚拟主机和本地服务器都测试过，针对有人发表评论，有人回复评论的邮件发送正常，但是，针对评论被站长审核通过的场景，无法发送邮件。如果打开插件的 debug 功能，查看 debug 信息，发现提示至少需要填写1个收件人。查看 debug 信息中，收件人信息确实为空的。然后我就去测试这个上述提到的 php 文件了，最后发现是传入 commendId 为空，所以获取不到评论对应的回信邮箱，导致的问题，请问您是如何追的呢？我可以自己按您的成功指引试一试。

**Comment by rakiy** [comment]
原来是这个场景，你将插件 plugin.php 第 328行 
```
self::sendMail($comment->coid, TRUE);
```
改为
```
self::sendMail($comment['coid'], TRUE);
```
或者改为
```
self::sendMail($comment->coid ?? $comment['coid'], TRUE);
```
即可

**Comment by xueshanlinghu** [comment]
非常感谢！实测成功！

**Comment by xueshanlinghu** [comment]
稍晚我提交一下修改稿，毕竟原作者不维护了

**Comment by xueshanlinghu** [comment]
PR 已提交，请仓库大大有空审核一下，谢谢您！
