### ISSUE TITLE
投稿插件： Akismet 评论过滤插件

### ISSUE THREAD

**Issue by LikeJson** [typecho-fans/plugins#128]
插件名称：Typecho 的 Akismet 评论插件

插件用处：
评论过滤插件

修改自 https://github.com/typecho/plugins/tree/master/Akismet

- 不再需要 php-curl 扩展
- 支持 ssl

**Comment by benzBrake** [comment]
https://github.com/typecho-fans/plugins/blob/master/TESTORE.md 列表里是有 Akismet 插件的
