### ISSUE TITLE
资料库是 sqlite3， 请问如何设定，谢谢

### ISSUE THREAD

**Issue by ck932** [typecho-fans/plugins#137]
同上

**Comment by benzBrake** [comment]
你用哪个插件遇到问题呢，提问三要素懂吗？

**Comment by ck932** [comment]
autobackup 装不了，启用的时候，报错如下：

Database Query Error

不知如何解决，在此先谢谢 :-)

**Comment by benzBrake** [comment]
autobackup 仅支持 mysql 吧，sqlite备份很简单啊，直接备份文件就行

**Comment by ck932** [comment]
明白了，谢过 :-)
