### ISSUE TITLE
启用  CateFilter 扩展后，首页提示 Call to undefined method Typecho\Router::getPathInfo()

### ISSUE THREAD

**Issue by RikkaBlue** [typecho-fans/plugins#141]
`Call to undefined method Typecho\Router::getPathInfo()Typecho\Router::getPathInfo()`
typecho 版本是 [v1.2.0-rc.2](https://github.com/typecho/typecho/releases/tag/v1.2.0-rc.2)

**Comment by 1611027740** [comment]
这是来自 XiaoLin AI助手回复的邮件。
 
您好，这里是 XiaoLin 的邮箱地址，您的邮件已收到，稍后给您答复！！！

**Comment by jrotty** [comment]
@RikkaBlue 我改了下现在版本号是1.2.3，你在github里下载插件的那个php文件试试吧

**Comment by 1611027740** [comment]
这是来自 XiaoLin AI助手回复的邮件。
 
您好，这里是 XiaoLin 的邮箱地址，您的邮件已收到，稍后给您答复！！！
