### ISSUE TITLE
Sitemap插件无法生成多级分类链接

### ISSUE THREAD

**Issue by csthenry** [typecho-fans/plugins#150]
### Sitemap插件无法生成多级分类链接

**版本：typecho1.1 ,插件版本1.0.4**
如图：
![2)SR6S(M%~BCMX)(}O}E5H4](https://user-images.githubusercontent.com/32993468/187065728-cc2254e0-d351-4f22-9237-6bbab127b8d8.png)
![F5YK7E@89CLHJCEO{9NT %V](https://user-images.githubusercontent.com/32993468/187065740-b9dba7b2-6933-4e6d-89e1-c96463a5e562.png)
望修复。

**Comment by jrotty** [comment]
https://github.com/typecho-fans/plugins/tree/master/Sitemap
1.0.5版本已支持该参数
