### ISSUE TITLE
投稿插件WindsCkEditor

### ISSUE THREAD

**Issue by awinds** [typecho-fans/plugins#161]
Typecho1.2编辑器插件ckEditor4最新版，支持上传图片附件，原附件管理点击插入 v1.0.0
地址：https://github.com/awinds/WindsCkEditor
下载：https://github.com/awinds/WindsCkEditor/archive/refs/tags/v1.0.0.zip

**Comment by benzBrake** [comment]
我先试试看看

**Comment by benzBrake** [comment]
用 editor 命名实例容器产生冲突，可以考虑用 WindsCkEditor 命名你的编辑器实例
