### ISSUE TITLE
未成功读取插件信息，请检查来源设置后重试。

### ISSUE THREAD

**Issue by jkjoy** [typecho-fans/plugins#167]
未成功读取插件信息，请检查来源[设置]后重试。

**Comment by benzBrake** [comment]
换源 jsdelivr

**Comment by benzBrake** [comment]
这个问题可能是  commit  e9a6fb6b4257252d4a9a14562f009e419e2d24d5 引起的，最新的 commit 97f215b3fea5776deec729621e7aaef62a324ad2 解决了这个问题
