### ISSUE TITLE
自制新插件 AutoSSL, 申请写权限

### ISSUE THREAD

**Issue by Aurorum-Studio** [typecho-fans/plugins#182]
投稿自制新插件AutoSSL, GitHub仓库：https://github.com/Aurorum-Studio/Typecho-AutoSSL
按照https://github.com/typecho-fans/plugins/blob/master/TESTORE.md的引导来提交Issue申请写权限

**Comment by benzBrake** [comment]
1.这个我觉得由 Typecho 实现不太好
2.为什么不是拦截路由而是直接写入文件

**Comment by Aurorum-Studio** [comment]
> 1.这个我觉得由 Typecho 实现不太好 2.为什么不是拦截路由而是直接写入文件

1. 我是觉得每三个月手动验证域名所有权，更新SSL证书实在是太烦了，特别是像我这样修改DNS记录还要挂VPN的😂
2. 直接写入文件是最简单的只需要在主机上操作，不需要去域名商网站修改DNS的验证方法（据我目前所知😂），这样实现逻辑简单，不易出错🦊

**Comment by Aurorum-Studio** [comment]
谢谢你通过我的Pull Request，我就关闭这个Issue啦🦊
