### ISSUE TITLE
启用了Ckeditor4Typecho后，文章编辑时为空白了

### ISSUE THREAD

**Issue by phoenixg** [typecho-fans/plugins#22]
typecho  版本 1.0 (14.10.10)
未装其他插件

**Comment by shingchi** [comment]
@zhulin3141

**Comment by zhulin3141** [comment]
@phoenixg, 我的没有这个问题，可以截个图吗？如果能把谷歌浏览器中用开发者工具中控制台中的信息也提供给我那就更好了。

**Comment by phoenixg** [comment]
![bugtypecho](https://cloud.githubusercontent.com/assets/990040/6436587/3b30d8e0-c0ed-11e4-801d-14d7fe619cc3.jpg)

**Comment by zhulin3141** [comment]
从图上来看是编辑器的语言文件加载的问题，考虑到其他的语言文件基本没有就只保留了简体中文，所以无法加载导致。
有2中方法解决：
* 修改插件中的config.js文件，添加配置 config.language = 'zh-cn';
* 从ckeditor的源码中提取en.js的语言文件放到lang目录中

**Comment by phoenixg** [comment]
用第一种方式修改config.js解决了， 谢谢！

**Comment by phoenixg** [comment]
顺便问下， 我想在不同文章运行不同的js脚本做demo的画，应该如何把js引入到文章里，并且用什么方式写js、div、css代码在文章中比较好？

**Comment by zhulin3141** [comment]
如果是代码量比较少的话，直接写编辑器里比较方便，不过大多数编辑器为了安全会过滤掉一些标签，如果代码量比较多的话自然单独写文件里更好些，你可以找找看有没有引入资源的插件

**Comment by phoenixg** [comment]
Thx
