### ISSUE TITLE
寻求帮助

### ISSUE THREAD

**Issue by bpplpp** [typecho-fans/plugins#30]
使用插件，卸载后有残留。上方菜单栏还有有：“RoutesHelper” 请问这个在哪里删除？谢谢

**Comment by binjoo** [comment]
重新安装插件，然后卸载。

**Comment by bpplpp** [comment]
宜昌市卸载安装再卸载，还是一样。AppStore也是这个情况

**Comment by jzwalk** [comment]
AppStore我这没发现禁用后菜单残留的情况。一般添加菜单项目的插件都会在public static function deactivate()下写有Helper::removePanel 正常会在插件禁用时删除菜单项的。如果你是因为没禁用插件就用FTP删除了插件文件，可以重新上传启用插件再禁用使其移除菜单。
此issue开了快一年了……如无问题就此关闭。
