### ISSUE TITLE
Baidu 翻译接口变了

### ISSUE THREAD

**Issue by gladuo** [typecho-fans/plugins#31]
http://api.fanyi.baidu.com/api/trans/product/apidoc 最好您更新一下

**Comment by gladuo** [comment]
会影响到 Autoslug 插件，原来的已经不可使用了

**Comment by doudoutime** [comment]
@shingchi

**Comment by shingchi** [comment]
@gladuo @doudoutime 更新了  好久没动过了  都不知道行不行。

**Comment by gladuo** [comment]
Good job. Thank you !
