### ISSUE TITLE
CkEditor4Typecho发表新文章时总会提示“要离开此网站吗？系统可能不会保存您所做的更改”

### ISSUE THREAD

**Issue by note4** [typecho-fans/plugins#32]
CkEditor4Typecho发表新文章时总会提示“要离开此网站吗？系统可能不会保存您所做的更改”

如果点击离开文章就会成功保存，如果点击了留下那发布按钮怎么点都不能提交内容了

typecho：版本 1.0 (14.10.10)
Ckeditor4Typecho：version 1.0.0

![image](https://cloud.githubusercontent.com/assets/6513389/14562076/37c34b4a-034d-11e6-8494-98cc0e264375.png)

**Comment by note4** [comment]
@zhulin3141   求指点！

**Comment by jzwalk** [comment]
js白痴表示不知道这提示哪来的……
插件261行有个“即将离开页面，是否确认编辑的内容已使用”提示，typecho的write-js.php有“内容已经改变尚未保存, 您确认要离开此页面吗?”提示，然并卵。。
@zhulin3141 还有谁能看出一二？ =.=

**Comment by jinfeijie** [comment]
```        
window.onbeforeunload = function(event){
    if(ckeditors.getData() != '' && {$isEdit}){
        event.returnValue = '即将离开页面，是否确认编辑的内容已使用？';   
    }
}
```
这段代码中，进行了一个判断，不在编辑的状态就提示“`即将离开页面，是否确认编辑的内容已使用？`”。
刺激的是，发布这个动作也是离开编辑的状态，所以就出现了这个情况。
@note4  如果你编辑习惯好的话，把`Plugin.php`文件中，`259`-`263`行代码删除就可以了。目测，删掉几乎没有任何影响。

不过，你最好打开`自动保存功能`，那就没有任何关系了。

**Comment by jzwalk** [comment]
感谢jinfeijie解答，看来应该是js判断与te有一点冲突0.0 问题不大，希望能帮到i主。如有其他问题欢迎继续提交！
