### ISSUE TITLE
删除插件后，面板没有被卸载

### ISSUE THREAD

**Issue by HeyChioy** [typecho-fans/plugins#37]
目前App Store插件和Sinauth插件遇到了这个情况

**Comment by chekun** [comment]
@HeyChioy , 我测试了一下没有问题，你的环境时如何的呢？

测试环境:

- Docker镜像 janes/alpine-lamp (Apache2, php5.6.28, MariaDB)
- Typecho 1.0 (14.10.10)

见Gif图(略大，加载需要点时间)：

![kapture 2017-03-07 at 14 10 51](https://cloud.githubusercontent.com/assets/1967804/23644140/a5fab5b4-0340-11e7-8e9e-af4dd67ab9c3.gif)

**Comment by HeyChioy** [comment]
Typecho 版本 1.0 (14.10.10) 
之前装App Store后第二天发现插件全被删除了，重装禁用之后没有面板菜单没有被卸载。
Sinauth 我看了下源码，deactive 方法没写卸载菜单和路由。
目前已通过新建插件-根据 Sinauth 源码自己写 卸载路由及面板菜单的方式解决，感谢回复。

**Comment by web3d** [comment]
我的锅
