### ISSUE TITLE
JSON插件怎么使用

### ISSUE THREAD

**Issue by lnzhangsong** [typecho-fans/plugins#45]

**Comment by lizheming** [comment]
安装插件之后会多出 `博客地址/api/接口名称` 这样的地址，例如 https://imnerd.org/api/posts ,具体有哪些接口名称可以看看代码 https://github.com/lizheming/JSON/blob/master/Action.php 写着 `//参数` 的注释下面的函数都可以作为接口名称，参数就在注释里写着。

**Comment by lnzhangsong** [comment]
谢谢
