### ISSUE TITLE
无法显示滑动条，无法提交评论

### ISSUE THREAD

**Issue by NoEggEgg** [typecho-fans/plugins#48]
# IQapTcha插件问题反馈

## 1.无法显示滑动条
经过检查，个人认为应该是自己站点启用https问题，遂将插件引用的js地址更改http→https。滑动条显示了。

## 2.无法提交评论
经过上步，滑动开始测试评论，滑动解锁了，点击提交后却提示需先滑动解锁...

提交这两条，希望有时间看看能不能更新一下插件，谢谢。

**Comment by jinfeijie** [comment]
1. 无法显示滑动条
* 【自己处理】似乎并没有什么用，等待作者处理 @byends 
* 【自动载入】可以直接把http去掉，可以兼容 http 和 https两种状态

2. 无法提交评论
后台如下图设置可以提交评论。可以提交一下php版本信息
![](https://user-images.githubusercontent.com/8290380/37507849-7ee1ff66-292b-11e8-91b5-178bada6016b.png)

**Comment by jzwalk** [comment]
880e37939d8c2acbdede8f241b3533707708e6a3 更新已修正js。https可以自己改下cdn地址。
