### ISSUE TITLE
上传文件后返回的path地址不正确。

### ISSUE THREAD

**Issue by chobitpapa** [typecho-fans/plugins#49]
Plugin.php 文件的 uploadHandle 方法，在 return 的时候 path 路径不对，少添加了 $filePath。

![image](https://user-images.githubusercontent.com/10645380/37769687-cb1e2d06-2e0c-11e8-8dea-b2629bf6ba24.png)

**Comment by wedojava** [comment]
你说的是哪个插件呢？

**Comment by chobitpapa** [comment]
QNUpload 这个插件  https://plugins.typecho.me/plugins/qnupload.html
