### ISSUE TITLE
和Codestyle 有冲突，语法高亮无法正常显示，

### ISSUE THREAD

**Issue by ghost** [typecho-fans/plugins#50]

**Comment by benzBrake** [comment]
什么插件啊。。。

**Comment by hongweipeng** [comment]
@Shadow-117 与哪个插件冲突？

**Comment by Shadow-117** [comment]
和@hongweipeng 的插件CodeStyle有冲突；还有TOC无法正常解析。

**Comment by DT27** [comment]
已修复，停用EditorMD插件重新下载覆盖所有文件后启用即可。

**Comment by jzwalk** [comment]
集群内也已拉取到最新版本 fa782cf3fbd7d34ddbc6ee5ae381427d7bdebbe2
