### ISSUE TITLE
使用部分主题后前段文章显示空白的

### ISSUE THREAD

**Issue by Jav4Boy** [typecho-fans/plugins#53]
LZ知道是什么原因吗?很多主题好像都不支持
![11](https://user-images.githubusercontent.com/37819737/39560059-71fbb518-4ecd-11e8-875d-2a543c26397d.jpg)
开启接管前台Markdown解析后
![22](https://user-images.githubusercontent.com/37819737/39560060-7237ddfe-4ecd-11e8-8852-e54795c90ebe.jpg)

**Comment by hongweipeng** [comment]
这可能是你还没掌握markdown的语法规则

**Comment by Jav4Boy** [comment]
...一样的文章,没有改动过

**Comment by jzwalk** [comment]
问题和本插件集群没关系，如果你是指[主题集群](https://github.com/typecho-fans/themes)里的作品，我这里测试也没发现类似问题。从截图看可能你的主题试图调用文内图片做摘要，在没有找到图片情况下显示空白，或有其他代码处理。
