### ISSUE TITLE
新版TeStore在哪里？

### ISSUE THREAD

**Issue by ylqjgm** [typecho-fans/plugins#57]
列表中的TeStore貌似没用啊

**Comment by jzwalk** [comment]
一直在测试细节，已经更新了：9c43a77bf1bebb2087ec8de70ebd05270a441683

**Comment by ylqjgm** [comment]
不行，还有问题的，首先Plugin.php第74行报错，是`Typecho_Widget_Helper_Form_Element_Textarea`，不是`Typecho_Widget_Helper_Form_Element_TextArea`
然后提交的配置数据不会保存，没仔细看，你检查下

**Comment by jzwalk** [comment]
确实有个大写问题，但我这PHP 5.6环境没报错 0_0 保存也是正常的，你用的环境是啥。。Typecho是1.1正式版吗？

**Comment by ylqjgm** [comment]
PHP 7.2，Typecho 1.1

**Comment by jzwalk** [comment]
修正了一版，PHP7.2.4下测试通过。
