### ISSUE TITLE
TeStore作者主页显示有错

### ISSUE THREAD

**Issue by ylqjgm** [typecho-fans/plugins#58]
请检查下，我这里显示的作者主页全是/admin/te-store/market

**Comment by jzwalk** [comment]
确实 = = 我改下

**Comment by jzwalk** [comment]
哦了，顺便又修了些安装上的问题，明儿准备正式发了。

**Comment by YinHeng89** [comment]
@jzwalk 请问下 阿里云虚拟主机  估计默认没开始openssl ，这种情况下 是不是获取不到  插件列表呢？

**Comment by jzwalk** [comment]
@YinHeng89 感谢提醒，刚发现很多基于云引擎主机开ssl都不允许抓取https - - 还好github能通过page功能提供普通协议页面，不过要改不少配置方面的东西，我再看看~

**Comment by YinHeng89** [comment]
@jzwalk 谢谢反馈，主要是对于很多普通用户来说虚拟主机操作比服务器入门难度低很多，但是不能使用插件更新的话，感觉很不方便~

**Comment by jzwalk** [comment]
@YinHeng89 搞定了，http用这两个地址就行：
http://typecho-fans.github.io/plugins/index.html 对应README.md
http://typecho-fans.github.io/plugins/TESTORE.html 对应TESTORE.md
和https的是同步的

**Comment by jzwalk** [comment]
又根据http页面抓取修正了插件的链接显示：6923dcef53ba5eac942a4e1ef64cfcde4e4e23e4
