### ISSUE TITLE
最新版TeStore反馈一个小问题

### ISSUE THREAD

**Issue by YinHeng89** [typecho-fans/plugins#60]
通过http获取到的插件列表，里面所有中文都是乱码~

**Comment by jzwalk** [comment]
专门用`<?xml encoding="utf-8" ?>`解决过这个问题啊，你的主机不识别么。。 是阿里云？= =
你可以自己针对性的改下Action.php的104行看：
```diff
-@$dom->loadHTML($html);
+@$dom->loadHTML(utf8_decode($html));
```
如果这个xml头无效的问题有普遍性，我回头再找找有没有更好的替代方法吧

**Comment by YinHeng89** [comment]
是阿里云的虚拟主机，用你提供的修改方法还是不能正确显示中文了，我觉得我应该换服务器，而不是一味的请求修改了~

**Comment by jzwalk** [comment]
@YinHeng89 阿里云还是有点代表性的。。你再试试改下面这种方法：
`@$dom->loadHTML(mb_convert_encoding($html, 'HTML-ENTITIES', 'UTF-8'));`
如果可行我下个版本用它

**Comment by jzwalk** [comment]
@YinHeng89 算了~ 忽然想到就算列表能用http源显示，zip包地址还是https。。这个没法替换，所以云主机还是不能用在线安装 - - 换主机商吧，ssl端口不开也算够抠搜的！
