### ISSUE TITLE
Call to a member function getAttribute() on null

### ISSUE THREAD

**Issue by legend-soft** [typecho-fans/plugins#61]
![image](https://user-images.githubusercontent.com/13842917/44315907-f9d07400-a45a-11e8-81ba-5b22d28c7245.png)
进入插件连页面大小都改了。。。。。。

**Comment by zhusaidong** [comment]
将`Action.php`的`122-129`行
替换为
```
if( $tdKey == 3 ){
	$href = '';
	foreach( $a as $key => $val ){
		$href .= ($key == 0 ? '' : ', ') . $val->getAttribute('href');
	}
}else{
	$href = $a->item(0)->getAttribute("href");
}
```

**Comment by zhusaidong** [comment]
作者链接那行如果没有链接会报错

**Comment by legend-soft** [comment]
原本代码跟这个一样的，缺省“href”属性一样报错。应该在取单条$href时，判断一下，如果没有该属性就给个空值好了。

**Comment by jzwalk** [comment]
已经修复了(感谢 @journey.ad )，顺便更新到1.1.2，改善其他各方面的兼容性问题。75ac6a592e8e05ee7df0d0aeb8838406a447a65c
