### ISSUE TITLE
使用了没有效果啊

### ISSUE THREAD

**Issue by Sagit-chu** [typecho-fans/plugins#63]
评论也没有极验啊，很奇怪

**Comment by Sagit-chu** [comment]
geetest   极验 for typecho

**Comment by jzwalk** [comment]
同名插件这里记录的有3款，如果你说的是这款：[https://github.com/typecho-fans/plugins/tree/master/GeeTest](https://github.com/typecho-fans/plugins/tree/master/GeeTest)注意看文档说明要填写响应的key和改模版文件中ID

**Comment by Sagit-chu** [comment]
我是按照readme弄的啊。。

**Comment by jzwalk** [comment]
@Sagit-chu 那就不清楚了。。我这记得测试是可以用的，你可以切换默认主题或试试其他几款看。

**Comment by Sagit-chu** [comment]
好吧

**Comment by luo-dan** [comment]
我的能用
好好用啊 大大提升码字配图的效率 大爱 赞 真棒

**Comment by Sagit-chu** [comment]
@luo-dan 我说的是极验。。。
