### ISSUE TITLE
没有找到任何插件，请检查插件源设置是否正确。

### ISSUE THREAD

**Issue by SorashitaInnei** [typecho-fans/plugins#73]
请问是什么原因呢 换curl也不行. 网站是用lnmp建立的. 如果有什么除了80 443 端口我也可以开一下 ,请告知 ,谢谢

**Comment by jzwalk** [comment]
先检查php.ini中allow_url_fopen是否为on，至少可以读取http页面，然后php_openssl扩展是否安装并启用了

**Comment by SorashitaInnei** [comment]
allow_url-fopen和openssl默认打开的.

**Comment by jzwalk** [comment]
那就不太清楚了。如果是访问github时网络不稳定，去插件设置里选不缓存换个时间段刷新重试下？

**Comment by SorashitaInnei** [comment]
升级php7.2.15解决
