### ISSUE TITLE
提示无法创建临时目录~~

### ISSUE THREAD

**Issue by ma3252788** [typecho-fans/plugins#75]
![](https://picgo-bed.oss-cn-beijing.aliyuncs.com/img/20190305225252.png)

**Comment by ma3252788** [comment]
https://picgo-bed.oss-cn-beijing.aliyuncs.com/img/20190305225252.png

**Comment by jzwalk** [comment]
如果指的是TeStore插件，手动在插件目录下新建名为.tmp的文件夹允许写入权限即可
