### ISSUE TITLE
想问一下有没有发布时同步到其他typecho的插件

### ISSUE THREAD

**Issue by eallion** [typecho-fans/plugins#76]
想问一下有没有发布时同步到其他typecho的插件

找了一圈，没有找到。

比如 a.com 准备发布一篇文章，发布时可以勾选是否同步发布到 b.com 。 通过xmlrpc协议应该能实现。

谢谢

**Comment by scvoet** [comment]
MySQL主从复制，了解一下

**Comment by jzwalk** [comment]
貌似还没有吧 0_0
