### ISSUE TITLE
投稿插件：鼠标漂浮字

### ISSUE THREAD

**Issue by icy2003** [typecho-fans/plugins#94]
插件名称：鼠标漂浮字（MouseFloating）
插件用处：点击网站空白处会漂浮出随机的设定好的列表里的文字
使用效果演示：
![image](https://user-images.githubusercontent.com/12480850/84659884-ad68f900-af4a-11ea-89e2-c1a05e129765.png)
![image](https://user-images.githubusercontent.com/12480850/84659931-ba85e800-af4a-11ea-89af-39b514df7a71.png)

github 地址：https://github.com/icy2003/typecho-MouseFloating

**Comment by jzwalk** [comment]
已添加 b156952 并发送邀请
