### ISSUE TITLE
投稿两个插件：登录美化插件和权限狗插件

### ISSUE THREAD

**Issue by jrotty** [typecho-fans/plugins#95]
登录美化插件，为注册/登录页面提供多种美化样式，还支持自定义背景图或者css
https://github.com/jrotty/LoginDesigner

权限狗插件
https://github.com/jrotty/Rdog
对普通用户而言
1，注册用户默认用户组可自由设置
2，支持贡献者发布文章自动审核
3，后台注册页面支持直接设置账号密码
对模板开发者而言
4，模板前台注册功能，注册用户可以设置自己的账户密码【typecho的注册功能默认是不支持用户设置密码的】
5，模板前台注册功能注册成功后的跳转地址可自定义【typecho默认是跳转到后台的】
6，前台发布文章，发布成功后的跳转地址自定义【默认是跳转后台文章列表页面】

鉴于我已经越来越不会用github了，所以麻烦了

**Comment by jlice** [comment]
给大佬安排上了

**Comment by jzwalk** [comment]
@jrotty 嗯你的免费作品我都已经优先整理收录了 ;)

**Comment by jzwalk** [comment]
@jrotty 我之前加到了TESTORE.md外链表中，通往你自己的维护目录。但我看 @jlice 兄弟是用subtree给你拉进了社区维护。如果你允许这里产生其他人修改的版本也行，只想自己维护的话就没必要了。你看呢？

**Comment by jrotty** [comment]
允许其他人修改哈。大家改才有意思

**Comment by jzwalk** [comment]
好的，确认下 :D 那我抽空就把外链里重复的条目去掉了
