### ISSUE TITLE
有没有更新 TeStore 插件自身的好办法？

### ISSUE THREAD

**Issue by eallion** [typecho-fans/plugins#96]
今天打开一个很久不用维护的站（企业站，不用维护），发现 TeStore 插件的版本还是 `1.1.2` 。
但是没有找到可更新自身的方式，只能 `停用` -> `删除` -> `重新上传`，或者 `卸载` -> `重新上传`

![GBZtIQ4t6l](https://user-images.githubusercontent.com/1698841/86513829-e99fc300-be3f-11ea-8d1d-3d5d74d1adfb.png)

**Comment by jzwalk** [comment]
你缓存是不是设的时间太长了？关闭缓存或在插件目录里删除list.json重新加载就好了

**Comment by jzwalk** [comment]
自我检测更新也可以，但必要性不太大，抽空再看

**Comment by eallion** [comment]
这个站有一年多没有登过后台了，缓存应该就是默认的 1 天，这种老版本的没法更新自己。
