### ISSUE TITLE
投稿插件：TEReplace文章内容替换插件

### ISSUE THREAD

**Issue by jrotty** [typecho-fans/plugins#97]
项目地址：https://github.com/jrotty/TEReplace

1，支持替换文章内容与标题
2，支持替换独立页面内容与标题
3，支持替换评论内容
4，支持替换评论的网址
5，支持替换fm字段内容(适用于Violet主题以及其他主题)
6，支持替换thumb字段内容(适用于影视一号/2号主题以及大量其他主题)
7，支持替换MP4字段内容(适用于影视一号/2号主题和Violet主题)

**Comment by jzwalk** [comment]
8f035a8 已录入社区维护，感谢投稿！
