### ISSUE TITLE
再投稿两个插件：影视采集插件与加密文章显示标题的插件

### ISSUE THREAD

**Issue by jrotty** [typecho-fans/plugins#98]
**影视采集插件**：https://github.com/jrotty/CatClaw
CatClaw，是一款纯免费的typecho影视采集插件，适用于typecho影视1号与影视2号模板，插件代码中含有typecho发布文章的接口代码，可以给需要的人做个参考。

**加密文章显示标题的插件**：https://github.com/jrotty/Titleshow
让加密文章的标题正常显示，让加密文章的标签正常显示，让加密文章的评论数正常显示，自定义所有加密文章的提示文字，意外的解决了加密文章无法评论的问题，意外的解决了加密文章返回403问题

**Comment by jzwalk** [comment]
8f035a8 已录入社区维护，感谢投稿！
