### ISSUE TITLE
网站后台开启https之后安装插件出现400

### ISSUE THREAD

**Issue by MUKAPP** [typecho-fans/plugins#99]
如下
400 Bad Request
The plain HTTP request was sent to HTTPS port
有点懵，求dalao们解答

**Comment by jzwalk** [comment]
Nginx的报错么，把ssl on去掉或者改成off看

**Comment by MUKAPP** [comment]
> Nginx的报错么，把ssl on去掉或者改成off看

这个试过了，但是没什么用。。。

**Comment by jzwalk** [comment]
那我也不懂了 = = 很少用Nginx，应该不是插件的问题

**Comment by ZiXia1** [comment]
你好，请在网站目录(非主题目录)的config.inc.php中添加
` /** 开启HTTPS */
define('__TYPECHO_SECURE__',true);`
试试呢
